# Generated by Django 3.1 on 2020-08-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('height', models.IntegerField(default=500)),
                ('width', models.IntegerField(default=500)),
                ('images1', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('images2', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('images3', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('images4', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('images5', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('images6', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('images7', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
