# Generated by Django 3.1 on 2020-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200827_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images1',
            field=models.ImageField(height_field='height', upload_to='Products', width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images2',
            field=models.ImageField(height_field='height', upload_to='Products', width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images3',
            field=models.ImageField(height_field='height', upload_to='Products', width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images4',
            field=models.ImageField(height_field='height', upload_to='Products', width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images5',
            field=models.ImageField(height_field='height', upload_to='Products', width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images6',
            field=models.ImageField(height_field='height', upload_to='Products', width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images7',
            field=models.ImageField(height_field='height', upload_to='Products', width_field='width'),
        ),
    ]
