# Generated by Django 3.1 on 2020-08-31 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200828_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 15, 1, 45, 1530)),
        ),
    ]
